### PR TITLE
WIP: Fix Robustness Test

### PR DESCRIPTION
**Pull request by caiotoledo**
Update files using dbus-cxx-2 methods.

### CODE REVIEW

**Comment by rm5248** [comment]
This looks pretty good to me(though I haven't tested it yet) - was there something else that was broken with it?

**Comment by caiotoledo** [comment]
> This looks pretty good to me(though I haven't tested it yet) - was there something else that was broken with it?

Indeed, the compilation is fine.

But when I build using the following commands:
```
mkdir -p .build && cd .build
cmake -DENABLE_ROBUSTNESS_TESTS=ON ../
make -j$(nproc)
```

And then try to run only the `robust-test` using:
```
ctest -V -R robust-test
```

The execution never ends, could you test on your side as well when you have time?

**Comment by rm5248** [comment]
It worked fine for me, although it took about 7-8 minutes on my machine.

I also chnaged the variables `times` and `numSignalsRx` in receive.cpp to be std::atomic, perhaps otherwise they're being optimized out?

You could also try disabling the logging, since it's probably not too useful for this test, as there is so much data going over the bus.

**Comment by caiotoledo** [comment]
> It worked fine for me, although it took about 7-8 minutes on my machine.

You're right, I've tested again and it took 6 and half minutes:
```
    Start 145: robust-test
1/1 Test #145: robust-test ......................   Passed  381.16 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 381.21 sec
```

So the Pull request is ready for merge, thanks @rm5248!

**Pull request merged**
